; CLW file contains information for the MFC ClassWizard

[General Info]
Version=1
LastClass=CAbortDlg
LastTemplate=CDialog
NewFileInclude1=#include "stdafx.h"
NewFileInclude2=#include "script1.h"
LastPage=0

ClassCount=1

ResourceCount=0
Class1=CAbortDlg

[CLS:CAbortDlg]
Type=0
HeaderFile=AbortDlg.h
ImplementationFile=AbortDlg.cpp
BaseClass=CDialog
Filter=D
LastObject=IDOK
VirtualFilter=dWC

